### ISSUE TITLE
Harvest and properties tables: 'show # of entries' does not work on Safari

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#88] opened 2016-06-29 04:47 UTC
Stays at 10 entries forever. Low priority of course ;)

Bug found on Mac 10.10:
Safari, doesn't work
Firefox, works well

**Comment by RignonNoel** [comment] 2016-07-02 19:11
Try to get a new version of datatables. But i don't find the problem on the web and it come from the `datatables` dependency

**Comment by tiagovaz** [comment] 2016-07-21 21:07
It seems the issue happens only in safari, seems not a bug from our side. Closing.

**Closed by tiagovaz** 2016-07-21 21:07 UTC
Labels: bug, help wanted
